CC=g++
CFLAGS=-std=c++14 -pedantic
OUTPUT=oop_exercise_02

all:
	$(CC) $(CFLAGS) bottle.cpp main.cpp -o $(OUTPUT)
run: 
	./$(OUTPUT) < test_01.txt
	./$(OUTPUT) < test_02.txt
	./$(OUTPUT) < test_03.txt